spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}

          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            redirectUri: "{baseUrl}/login/oauth2/code/{registrationId}"

  datasource:
#    url: jdbc:postgresql://${POSTGRESQL_HOST:localhost}/${DB_NAME:reviews_db}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        show-sql: true
        format-sql: true
        search:
          default:
            directory_provider: filesystem
            indexBase: ./hibernate.search.index


app:
  allowedCorsOrigin: http://localhost:3000
#  defaultRedirectUrl: http://localhost:3000/redirect
  defaultRedirectUrl: /redirect
  jwt:
    secret: ${JWT_SECRET}
    lifetime: 12
